# Generated by Django 3.0.7 on 2020-06-26 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='statustext',
            field=models.CharField(default='', max_length=256),
        ),
    ]
